### ISSUE TITLE
Crash Talkable notifyOriginDidRegister:withWebView:]

### ISSUE THREAD

**Issue by mihaicris-adoreme** [talkable/ios-sdk#19] opened 2022-08-31 14:29 UTC
Hi, we are having this crash, could you please tell us what could be the reason? Do you need more information for investigation?
Thank you.

```sh
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  AdoreMe                        0x1161368 -[Talkable notifyOriginDidRegister:withWebView:] + 549796
2  AdoreMe                        0x115baa0 __34-[Talkable registerOrigin:params:]_block_invoke_2.204 + 527068
3  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
5  libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
6  libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
7  CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0xb704 __CFRunLoopRun + 2532
9  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
10 GraphicsServices               0x1374 GSEventRunModal + 164
11 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
12 UIKitCore                      0x296090 UIApplicationMain + 364
13 libswiftUIKit.dylib            0x30ecc UIApplicationMain(_:_:_:_:) + 104
14 AdoreMe                        0x3b93c main + 4301224252 (EliteAccountDashboardViewController.swift:4301224252)
15 ???                            0x104909da4 (Missing)
```

**Device**
Model:iPhone 12 Pro
Orientation: Face Up
RAM free: 139.52 MB
Disk free: 36.07 GB

**Operating System**
Version:15.6.1
Orientation: Portrait
Jailbroken:No

**Comment by dgtv** [comment] 2022-09-02 10:19
Hi @mihaicris-adoreme,
Look like we need more info to investigate it properly.
Does your delegate implement `didRegisterOrigin:withWebView:`? And is this an often issue or happens time-to-time? Maybe there are some steps to reproduce to get the error? Thanks

**Comment by mihaicris-adoreme** [comment] 2022-09-07 13:33
Hi @dgtv ,

It is happening from time to time, we had around 50 crashes in the last 90 days.

We do not implement that method. This is how it is implemented: 

```swift
extension ReferralViewController: TalkableDelegate {
    func shouldPresentTalkableOffer(_ controller: UIViewController!) -> Bool {
        false
    }

    func viewControllerForPresentingTalkableOfferViewController() -> UIViewController {
        self
    }

    func shouldRegister(_ type: TKBLOriginType, with url: URL) -> Bool {
        webView.load(URLRequest(url: url))
        return true
    }
}
```

This is another crash from 2 days ago. We are using latest Talkable SDK version.

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000080000020

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  AdoreMe                        0x114defc -[TKBLOfferViewController publishMessageNotification:] + 468904
2  CoreFoundation                 0x2a834 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
3  CoreFoundation                 0xc6fd4 ___CFXRegistrationPost_block_invoke + 52
4  CoreFoundation                 0x9a1d0 _CFXRegistrationPost + 456
5  CoreFoundation                 0x408ac _CFXNotificationPost + 728
6  Foundation                     0x1b734 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
7  AdoreMe                        0x1157ee0 -[TKBLOfferTarget notifyMessage:withParams:sender:] + 509836
8  AdoreMe                        0x1157b00 -[TKBLOfferTarget userContentController:didReceiveScriptMessage:] + 508844
9  WebKit                         0x2f23e8 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&) + 208
10 WebKit                         0x69ad80 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&) + 712
11 WebKit                         0x9e218c WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 2384
12 WebKit                         0x398e10 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 448
13 WebKit                         0x5e516c WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 40
14 WebKit                         0x37e2f0 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 264
15 WebKit                         0x37db08 IPC::Connection::dispatchIncomingMessages() + 468
16 JavaScriptCore                 0x4f2d0 WTF::RunLoop::performWork() + 200
17 JavaScriptCore                 0x5006c WTF::RunLoop::performWork(void*) + 36
18 CoreFoundation                 0xbb414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
19 CoreFoundation                 0xcc1a0 __CFRunLoopDoSource0 + 208
20 CoreFoundation                 0x5694 __CFRunLoopDoSources0 + 268
21 CoreFoundation                 0xb05c __CFRunLoopRun + 828
22 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
23 GraphicsServices               0x1374 GSEventRunModal + 164
24 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
25 UIKitCore                      0x296090 UIApplicationMain + 364
26 libswiftUIKit.dylib            0x30ecc UIApplicationMain(_:_:_:_:) + 104
27 AdoreMe                        0x3c090 main + 4342825104 (EliteAccountDashboardViewController.swift:4342825104)
28 ???                            0x10236dda4 (Missing)
```

**Device**
Model:iPhone 12
Orientation: Portrait
RAM free: 81.27 MB
Disk free: 79.7 GB

**Operating System**
Version:15.6.1
Orientation: Portrait
Jailbroken:No

**Crash**
Date:Sep 5, 2022, 3:19:51 AM

**Comment by dgtv** [comment] 2022-09-12 14:41
@mihaicris-adoreme Thanks for the details! Looks like the problem is caused by a deallocated `webView` object. Can you please describe about `webView` object from your example: what is it, where do you create it and how do you use it?
```swift
extension ReferralViewController: TalkableDelegate {
    func shouldRegister(_ type: TKBLOriginType, with url: URL) -> Bool {
        webView.load(URLRequest(url: url))
        return true
    }
}
```

**Comment by mihaicris-adoreme** [comment] 2022-09-13 13:46
@dgtv Thanks for checking!

The implementation was with our own WKWebview instance in order to control its delegate `WKNavigationDelegate`, and this instance was created before calling Talkable SDK `register: params:`. However, I made a change now to the code in order to implement `didRegisterOrigin:withWebView:`, thus using the webview of SDKs instead of ours, hopefully the bug will not occur anymore. We will monitor the hotfix release and let you know if the crash still happening.

**Comment by dgtv** [comment] 2022-09-13 15:02
@mihaicris-adoreme Thanks for the update! Hope it will fix the problem.
The SDK was designed in the way that it's WKWebview should be used, so potential problems with deallocation is not the only problem that can raise if external WKWebview is used instead.

**Comment by dgtv** [comment] 2022-09-22 19:58
@mihaicris-adoreme Can you please tell if the issue still occurs or we can close the ticket? Thanks

**Comment by mihaicris-adoreme** [comment] 2022-09-23 07:30
@dgtv Yes, we still have the crash. Here is the crash log and the implementation.
Any idea, what is wrong in our implementation? Or is it the library SDK that has an issue? 
Could you please investigate further?
Thank you. 


```sh
iOS 15.6.1
iPhone 11

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x004c656c7070451a

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1fcc objc_msgSend + 172
1  AdoreMe                        0x11611c8 -[Talkable notifyOriginDidRegister:withWebView:] + 549892
2  AdoreMe                        0x115b900 __34-[Talkable registerOrigin:params:]_block_invoke_2.204 + 527164
3  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
5  libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
6  libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
7  CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0xb704 __CFRunLoopRun + 2532
9  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
10 GraphicsServices               0x1374 GSEventRunModal + 164
11 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
12 UIKitCore                      0x296090 UIApplicationMain + 364
13 libswiftUIKit.dylib            0x30ecc UIApplicationMain(_:_:_:_:) + 104
14 AdoreMe                        0x38a40 main + 4335585856 (AccountEmailRequestPresenter.swift:4335585856)
15 ???                            0x102129da4 (Missing)
```


```swift
import SnapKit
import TalkableSDK
import UIKit

final class ReferralViewController: UIViewController {
    private let activityIndicator = UIActivityIndicatorView()
    private let navigationBar = UINavigationBar()

    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()

        guard let customer = UserSession.shared.loggedInUser() else { return }
        setupTalkable(campaign: "ios-invite", customer: customer)
        activityIndicator.startAnimating()
    }

    private func setupTalkable(campaign: String, customer: Customer) {
        guard let manager = Talkable.manager() else { return }
        manager.delegate = self
        manager.register(
            TKBLOriginType.affiliateMember,
            params: [
                TKBLCampaignTags: campaign,
                TKBLAffiliateMemberKey: [
                    TKBLAffiliateMemberEmailKey: customer.getEmail(),
                    TKBLAffiliateMemberFirstNameKey: customer.getFirstName(),
                    TKBLAffiliateMemberCustomerIDKey: customer.getCustomerId()
                ]
            ]
        )
    }

    // MARK: - Helpers

    private func setupViews() {
        view.backgroundColor = .systemBackground
        view.addSubview(navigationBar)
        view.addSubview(activityIndicator)

        let item = UINavigationItem()
        item.title = "Refer a friend".localized
        item.leftBarButtonItem = UIBarButtonItem(
            image: UIImage(named: "close_nav_icon"), style: .plain, target: self,
            action: #selector(onDismissBarButtonTapped)
        )
        navigationBar.items = [item]

        activityIndicator.snp.makeConstraints { make in
            make.center.equalToSuperview()
        }
        navigationBar.snp.makeConstraints { make in
            make.left.right.top.equalToSuperview()
        }
    }

    @objc private func onDismissBarButtonTapped(_ sender: Any) {
        self.dismiss(animated: true)
    }
}

extension ReferralViewController: TalkableDelegate {
    func shouldPresentTalkableOffer(_ controller: UIViewController!) -> Bool {
        false
    }

    func viewControllerForPresentingTalkableOfferViewController() -> UIViewController {
        self
    }

    func didRegister(_ type: TKBLOriginType, with webView: WKWebView!) {
        activityIndicator.stopAnimating()
        guard let webView = webView else { return }
        view.insertSubview(webView, belowSubview: activityIndicator)
        webView.snp.makeConstraints { make in
            make.left.right.bottom.equalToSuperview()
            make.top.equalTo(navigationBar.snp.bottom).offset(1)
        }
    }
}

```

**Comment by dgtv** [comment] 2022-09-23 15:34
@mihaicris-adoreme Thanks for the reply and details! I'll take a looks at this, but please notice that it will be on a week after the next as I'll be unavailable till this date

**Comment by dgtv** [comment] 2022-10-11 14:05
Hi @mihaicris-adoreme,
From my point what I see it looks like your implementations is ok. Thanks for the code, it is very helpful!
I tried to reproduce the same setup for me but didn't get the crash and without this it is hard to say what is wrong, sorry for that.
Maybe you were able to notice additional info regarding the crash? Do crashes after moving to the SDK's Webview became less frequent and how frequent they are now?

Thanks.
And sorry for the late response

**Comment by mihaicris-adoreme** [comment] 2022-10-13 08:09
Hi @dgtv,

It has the same occurrence rate.
I was able to catch the bug in Xcode, I sent you on email the stack trace and some screenshots

Let me know if this helps.

Thanks

**Comment by dgtv** [comment] 2022-10-17 18:50
Hi @mihaicris-adoreme,
Thanks for the info and especially for the stack trace.

From it I see that the error happens on `activityIndicator.stopAnimating()` call so it looks like the issue is not caused by the  SDK. Probably the problem is caused because `activityIndicator` is not always available in the context of the delegate's `didRegisterOrigin:withWebView` for some reason and you should manipulate with the indicator in a different way. But unfortunately I can't help you with it. I just found that people sometimes have issues with `activityIndicator` when using `hidden` property as described here for example: https://stackoverflow.com/a/31931367.

Also please notice that Talkable SDK runs `didRegisterOrigin:withWebView` of the delegate on the main thread as looks like currently it is not clear from the documentation:
https://github.com/talkable/ios-sdk/blob/ebd1d3b764d3dc5bdee5b6e39d20a479b5e139ff/Talkable/Talkable.m#L306
https://github.com/talkable/ios-sdk/blob/ebd1d3b764d3dc5bdee5b6e39d20a479b5e139ff/Talkable/Talkable.m#L321


Hope it was helpful.
Thanks

**Comment by mihaicris-adoreme** [comment] 2022-10-18 09:29
Hi, thanks.

I made a change in how we show the webview over the activity indicator, thus we do not access the indicator at all in that context (although it is very strange, the indicator has a strong reference in the class, and it is accessed on the main thread, so it should always be available). 

I will see if the bug is solved and close this issue as well.

**Comment by mihaicris-adoreme** [comment] 2022-11-18 15:48
Hi, 

We still have the crash 13 occurrences
-[Talkable notifyOriginDidRegister:withWebView:]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  AdoreMe                        0x13cb8d8 -[Talkable notifyOriginDidRegister:withWebView:] + 549404
2  AdoreMe                        0x13c667c __34-[Talkable registerOrigin:params:]_block_invoke_2.204 + 528320
3  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
5  libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
6  libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
7  CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0xb704 __CFRunLoopRun + 2532
9  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
10 GraphicsServices               0x1374 GSEventRunModal + 164
11 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
12 UIKitCore                      0x296090 UIApplicationMain + 364
13 libswiftUIKit.dylib            0x30ecc UIApplicationMain(_:_:_:_:) + 104
14 AdoreMe                        0x2f148 main + 4375507272 (AccountEmailRequestPresenter.swift:4375507272)
15 ???                            0x107081da4 (Missing)
```


And a new crash 3 occurrences

-[TKBLOfferViewController publishMessageNotification:]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  AdoreMe                        0x114defc -[TKBLOfferViewController publishMessageNotification:] + 468904
2  CoreFoundation                 0x2a834 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
3  CoreFoundation                 0xc6fd4 ___CFXRegistrationPost_block_invoke + 52
4  CoreFoundation                 0x9a1d0 _CFXRegistrationPost + 456
5  CoreFoundation                 0x408ac _CFXNotificationPost + 728
6  Foundation                     0x1b734 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
7  AdoreMe                        0x1157ee0 -[TKBLOfferTarget notifyMessage:withParams:sender:] + 509836
8  AdoreMe                        0x1157b00 -[TKBLOfferTarget userContentController:didReceiveScriptMessage:] + 508844
9  WebKit                         0x2f23e8 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&) + 208
10 WebKit                         0x69ad80 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&) + 712
11 WebKit                         0x9e218c WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 2384
12 WebKit                         0x398e10 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 448
13 WebKit                         0x5e516c WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 40
14 WebKit                         0x37e2f0 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 264
15 WebKit                         0x37db08 IPC::Connection::dispatchIncomingMessages() + 468
16 JavaScriptCore                 0x4f2d0 WTF::RunLoop::performWork() + 200
17 JavaScriptCore                 0x5006c WTF::RunLoop::performWork(void*) + 36
18 CoreFoundation                 0xbb414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
19 CoreFoundation                 0xcc1a0 __CFRunLoopDoSource0 + 208
20 CoreFoundation                 0x5694 __CFRunLoopDoSources0 + 268
21 CoreFoundation                 0xb05c __CFRunLoopRun + 828
22 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
23 GraphicsServices               0x1374 GSEventRunModal + 164
24 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
25 UIKitCore                      0x296090 UIApplicationMain + 364
26 libswiftUIKit.dylib            0x30ecc UIApplicationMain(_:_:_:_:) + 104
27 AdoreMe                        0x3c090 main + 4337565840 (EliteAccountDashboardViewController.swift:4337565840)
28 ???                            0x106d8dda4 (Missing)
```

**Closed as not planned** 2024-02-24 19:24 UTC
